//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaxtaskra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gjaldskra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gjaldskra()
        {
            this.Gjaldskra_Product = new HashSet<Gjaldskra_Product>();
        }
    
        public int GjaldskraID { get; set; }
        public string Númer { get; set; }
        public string Heiti { get; set; }
        public decimal Fjárhæð { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gjaldskra_Product> Gjaldskra_Product { get; set; }
    }
}
