//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaxtaskra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInterest
    {
        public int ProductInterestsID { get; set; }
        public int Product_indexationID { get; set; }
        public int VaxtaRunaIntID { get; set; }
    
        public virtual Product_indexation Product_indexation { get; set; }
        public virtual Vaxtaruna_interests Vaxtaruna_interests { get; set; }
    }
}
