//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaxtaskra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaxtasaga
    {
        public int Id { get; set; }
        public int VaxtarunaID { get; set; }
        public int VaxtafoturID { get; set; }
        public decimal Spread { get; set; }
        public decimal Vaxtafotur { get; set; }
        public System.DateTime Date { get; set; }
        public decimal VextirTotal { get; set; }
    }
}
