//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaxtaskra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaxtafotur_interests
    {
        public int Vaxtafotur_interestsID { get; set; }
        public int VaxtafoturId { get; set; }
        public decimal Interest { get; set; }
        public System.DateTime Date { get; set; }
        public int Is_Current { get; set; }
    
        public virtual Vaxtafotur Vaxtafotur { get; set; }
    }
}
