//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaxtaskra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaxtaruna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vaxtaruna()
        {
            this.Vaxtaruna_interests = new HashSet<Vaxtaruna_interests>();
        }
    
        public int VaxtarunaID { get; set; }
        public string Heiti { get; set; }
        public int Vextir_greidastID { get; set; }
        public bool Is_deposit { get; set; }
        public bool Is_fixed { get; set; }
        public bool Is_indexed { get; set; }
        public int VaxtafoturID { get; set; }
        public Nullable<decimal> Amount_from { get; set; }
        public Nullable<decimal> Amount_to { get; set; }
        public Nullable<decimal> Months_tied { get; set; }
        public Nullable<bool> is_Corp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaxtaruna_interests> Vaxtaruna_interests { get; set; }
        public virtual Vextir_greidast Vextir_greidast { get; set; }
        public virtual Vaxtafotur Vaxtafotur { get; set; }
    }
}
