//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaxtaskra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaxtafotur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vaxtafotur()
        {
            this.Vaxtafotur_interests = new HashSet<Vaxtafotur_interests>();
            this.Vaxtarunas = new HashSet<Vaxtaruna>();
        }
    
        public int VaxtafoturID { get; set; }
        public string Heiti { get; set; }
        public Nullable<bool> Is_Indexed { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaxtafotur_interests> Vaxtafotur_interests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaxtaruna> Vaxtarunas { get; set; }
    }
}
