//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaxtaskra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaxtaruna_interests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vaxtaruna_interests()
        {
            this.ProductInterests = new HashSet<ProductInterest>();
        }
    
        public int Vaxtaruna_InterestsID { get; set; }
        public decimal Spread { get; set; }
        public System.DateTime Date { get; set; }
        public int VaxtarunaID { get; set; }
        public Nullable<int> is_current { get; set; }
    
        public virtual Vaxtaruna Vaxtaruna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInterest> ProductInterests { get; set; }
    }
}
